USE DATABASE GLOBAL_MART_DB;
USE SCHEMA STORAGE_INTEGRATIONS;

CREATE OR REPLACE STORAGE INTEGRATION S3_INTEGRATION
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_ALLOWED_LOCATIONS = (
    's3://globalmart-datalake/'
);

-- Verify Storage Integration
DESC STORAGE INTEGRATION S3_INTEGRATION;
