USE DATABASE GLOBAL_MART_DB;
USE SCHEMA STORAGE_INTEGRATIONS;

-- CSV File Format
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', '');

-- JSON File Format
CREATE OR REPLACE FILE FORMAT JSON_FORMAT
TYPE = JSON
STRIP_OUTER_ARRAY = TRUE;

-- Verify File Formats
SHOW FILE FORMATS;
