USE DATABASE GLOBAL_MART_DB;
USE SCHEMA STORAGE_INTEGRATIONS;

CREATE OR REPLACE STAGE S3_STAGE
URL = 's3://globalmart-datalake/transactions/'
STORAGE_INTEGRATION = S3_INTEGRATION
FILE_FORMAT = CSV_FORMAT;

-- Verify Stage
DESC STAGE S3_STAGE;

-- List Files
LIST @S3_STAGE;
