USE DATABASE GLOBAL_MART_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE POS_BATCH
(
    TRANSACTION_ID      NUMBER,
    STORE_ID            NUMBER,
    STORE_NAME          STRING,
    STORE_CITY          STRING,
    CUSTOMER_ID         NUMBER,
    PRODUCT_ID          NUMBER,
    PRODUCT_NAME        STRING,
    CATEGORY            STRING,
    QUANTITY            NUMBER,
    UNIT_PRICE          NUMBER(10,2),
    TOTAL_AMOUNT        NUMBER(10,2),
    PAYMENT_METHOD      STRING,
    TRANSACTION_DATE    DATE,
    TRANSACTION_TIME    STRING
);

-- Verify Table
DESC TABLE POS_BATCH;
